kafka:
  bootstrap_servers:
    - sckafka1.simcenter.utc.edu:9092
    - sckafka2.simcenter.utc.edu:9092
    - sckafka3.simcenter.utc.edu:9092

sensors:
  - topic: MLK_PEEPLES_AIR_QUALITY
    mac: 84:f3:eb:91:44:38
    location: mlk-peeples
  - topic: MLK_CENTRAL_AIR_QUALITY
    mac: 84:f3:eb:44:d8:24
    location: mlk-central
  - topic: MLK_DOUGLAS_AIR_QUALITY
    mac: 84:f3:eb:91:44:60
    location: mlk-douglas
  - topic: MLK_MAGNOLIA_AIR_QUALITY
    mac: 84:f3:eb:45:1a:53
    location: mlk-magnolia
  - topic: MLK_GEORGIA_AIR_QUALITY
    mac: 84:f3:eb:45:1a:66
    location: mlk-georgia
  - topic: MLK_LINDSAY_AIR_QUALITY
    mac: 84:f3:eb:45:31:54
    location: mlk-lindsay
  - topic: MLK_HOUSTON_AIR_QUALITY
    mac: 84:f3:eb:45:23:4c
    location: mlk-houston